/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:37:06â€¯PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@class NSArray, _UIVisualEffectViewBackdropCaptureGroup, UIView, NSString;

@interface _UIVisualEffectSubview : UIView {
	NSArray* _filters;
	NSArray* _viewEffects;
}

@property (assign,nonatomic) BOOL disableGroupFiltering; 
@property (nonatomic,retain) _UIVisualEffectViewBackdropCaptureGroup * primaryCaptureGroup;               //@synthesize primaryCaptureGroup=_primaryCaptureGroup - In the implementation block
@property (nonatomic,copy) NSArray * viewEffects;                                                         //@synthesize viewEffects=_viewEffects - In the implementation block
@property (nonatomic,copy) NSArray * filters;                                                             //@synthesize filters=_filters - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setFilters:(NSArray *)arg1 ;
-(void)layoutSubviews;
-(void)_monitoredView:(id)arg1 willMoveFromSuperview:(id)arg2 toSuperview:(id)arg3 ;
-(NSArray *)filters;
-(void)setDisableGroupFiltering:(BOOL)arg1 ;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(void)setPrimaryCaptureGroup:(_UIVisualEffectViewBackdropCaptureGroup *)arg1 ;
-(void)applyIdentityFilterEffects;
-(void)applyRequestedFilterEffects;
-(void)applyRequestedViewEffects;
-(void)applyIdentityViewEffects;
-(_UIVisualEffectViewBackdropCaptureGroup *)primaryCaptureGroup;
-(NSArray *)viewEffects;
-(void)willMoveToWindow:(id)arg1 ;
-(void)setViewEffects:(NSArray *)arg1 ;
-(BOOL)disableGroupFiltering;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)_initialValueForLayer:(id)arg1 keyPath:(id)arg2 usePresentationValue:(BOOL)arg3 ;
@end

