/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:41â€¯PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@class CAFilter, NSString, NSDictionary;

@interface _UIVisualEffectFilterEntry : NSObject {

	CAFilter* _filter;
	BOOL _useRelaxedDiffingRule;
	NSString* _filterType;
	NSDictionary* _configurationValues;
	NSDictionary* _requestedValues;
	NSDictionary* _identityValues;
	double _requestedScaleHint;
	double _identityScaleHint;
	NSString* _filterName;

}

@property (nonatomic,copy) NSString * filterType;                           //@synthesize filterType=_filterType - In the implementation block
@property (nonatomic,copy) NSDictionary * configurationValues;              //@synthesize configurationValues=_configurationValues - In the implementation block
@property (nonatomic,copy) NSDictionary * requestedValues;                  //@synthesize requestedValues=_requestedValues - In the implementation block
@property (nonatomic,copy) NSDictionary * identityValues;                   //@synthesize identityValues=_identityValues - In the implementation block
@property (assign,nonatomic) double requestedScaleHint;                     //@synthesize requestedScaleHint=_requestedScaleHint - In the implementation block
@property (assign,nonatomic) double identityScaleHint;                      //@synthesize identityScaleHint=_identityScaleHint - In the implementation block
@property (assign,nonatomic) BOOL useRelaxedDiffingRule;                    //@synthesize useRelaxedDiffingRule=_useRelaxedDiffingRule - In the implementation block
@property (nonatomic,readonly) CAFilter * filter; 
@property (nonatomic,copy,readonly) NSString * filterName;                  //@synthesize filterName=_filterName - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setRequestedValues:(NSDictionary *)arg1 ;
-(id)valueAsRequested:(BOOL)arg1 ;
-(NSDictionary *)configurationValues;
-(id)initWithFilterType:(id)arg1 configurationValues:(id)arg2 requestedValues:(id)arg3 identityValues:(id)arg4 ;
-(NSString *)filterType;
-(NSDictionary *)identityValues;
-(void)setIdentityValues:(NSDictionary *)arg1 ;
-(void)setFilterType:(NSString *)arg1 ;
-(void)setIdentityScaleHint:(double)arg1 ;
-(void)convertToIdentity;
-(double)scaleHintAsRequested:(BOOL)arg1 ;
-(void)setRequestedScaleHint:(double)arg1 ;
-(CAFilter *)filter;
-(void)setUseRelaxedDiffingRule:(BOOL)arg1 ;
-(BOOL)isSameTypeOfEffect:(id)arg1 ;
-(id)copyForTransitionOut;
-(BOOL)canTransitionToEffect:(id)arg1 ;
-(BOOL)useRelaxedDiffingRule;
-(double)identityScaleHint;
-(void)forceUniqueName;
-(NSString *)filterName;
-(double)requestedScaleHint;
-(id)copyForTransitionToEffect:(id)arg1 ;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSDictionary *)requestedValues;
-(void)setConfigurationValues:(NSDictionary *)arg1 ;
@end

