/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:38:29 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/UIKitServices.framework/UIKitServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UISUserInterfaceStyleModeDelegate;
@interface UISUserInterfaceStyleMode : NSObject /*{

	id<UISUserInterfaceStyleModeDelegate> _delegate;
	BOOL _observingDefaults;
}*/
@property (assign,nonatomic) long long modeValue; 
@property (nonatomic,readonly) long long suggestedAutomaticModeValue; 
/*@property (assign,nonatomic) SCD_Struct_UI7 override; 
@property (assign,nonatomic) SCD_Struct_UI8 customSchedule; 
-(SCD_Struct_UI8)customSchedule;
-(SCD_Struct_UI7)override;
-(id)initWithDelegate:(id)arg1 ;
-(void)_setOverride:(SCD_Struct_UI7)arg1 force:(BOOL)arg2 ;
-(void)dealloc;
-(void)setCustomSchedule:(SCD_Struct_UI8)arg1 ;
-(long long)suggestedAutomaticModeValue;
-(id)_commonAnalyticsEventDictionary;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;*/
-(void)setModeValue:(long long)arg1 ;
//-(void)setOverride:(SCD_Struct_UI7)arg1 ;
-(long long)modeValue;
@end

